import { defineDelamain } from "als:authoring";

export const delamain = defineDelamain({
  phases: ["analysis", "closed"],
  states: {
    p01: { initial: true, phase: "analysis", actor: "agent", provider: "anthropic", resumable: false, path: "agents/p01.md" },
    p02: { phase: "analysis", actor: "agent", provider: "anthropic", resumable: false, path: "agents/p02.md" },
    p03: { phase: "analysis", actor: "agent", provider: "anthropic", resumable: false, path: "agents/p03.md" },
    p04: { phase: "analysis", actor: "agent", provider: "anthropic", resumable: false, path: "agents/p04.md" },
    p05: { phase: "analysis", actor: "agent", provider: "anthropic", resumable: false, path: "agents/p05.md" },
    p06: { phase: "analysis", actor: "agent", provider: "anthropic", resumable: false, path: "agents/p06.md" },
    p07: { phase: "analysis", actor: "agent", provider: "anthropic", resumable: false, path: "agents/p07.md" },
    p08: { phase: "analysis", actor: "agent", provider: "anthropic", resumable: false, path: "agents/p08.md" },
    p09: { phase: "analysis", actor: "agent", provider: "anthropic", resumable: false, path: "agents/p09.md" },
    p10: { phase: "analysis", actor: "agent", provider: "anthropic", resumable: false, path: "agents/p10.md" },
    p11: { phase: "analysis", actor: "agent", provider: "anthropic", resumable: false, path: "agents/p11.md" },
    p12: { phase: "analysis", actor: "agent", provider: "anthropic", resumable: false, path: "agents/p12.md" },
    "failed-p01": { phase: "analysis", actor: "operator" },
    "failed-p02": { phase: "analysis", actor: "operator" },
    "failed-p03": { phase: "analysis", actor: "operator" },
    "failed-p04": { phase: "analysis", actor: "operator" },
    "failed-p05": { phase: "analysis", actor: "operator" },
    "failed-p06": { phase: "analysis", actor: "operator" },
    "failed-p07": { phase: "analysis", actor: "operator" },
    "failed-p08": { phase: "analysis", actor: "operator" },
    "failed-p09": { phase: "analysis", actor: "operator" },
    "failed-p10": { phase: "analysis", actor: "operator" },
    "failed-p11": { phase: "analysis", actor: "operator" },
    "failed-p12": { phase: "analysis", actor: "operator" },
    complete: { phase: "closed", terminal: true },
  },
  transitions: [
    { class: "advance", from: "p01", to: "p02" },
    { class: "advance", from: "p02", to: "p03" },
    { class: "advance", from: "p03", to: "p04" },
    { class: "advance", from: "p04", to: "p05" },
    { class: "advance", from: "p05", to: "p06" },
    { class: "advance", from: "p06", to: "p07" },
    { class: "advance", from: "p07", to: "p08" },
    { class: "advance", from: "p08", to: "p09" },
    { class: "advance", from: "p09", to: "p10" },
    { class: "advance", from: "p10", to: "p11" },
    { class: "advance", from: "p11", to: "p12" },
    { class: "exit", from: "p12", to: "complete" },
    { class: "rework", from: "p01", to: "failed-p01" },
    { class: "rework", from: "p02", to: "failed-p02" },
    { class: "rework", from: "p03", to: "failed-p03" },
    { class: "rework", from: "p04", to: "failed-p04" },
    { class: "rework", from: "p05", to: "failed-p05" },
    { class: "rework", from: "p06", to: "failed-p06" },
    { class: "rework", from: "p07", to: "failed-p07" },
    { class: "rework", from: "p08", to: "failed-p08" },
    { class: "rework", from: "p09", to: "failed-p09" },
    { class: "rework", from: "p10", to: "failed-p10" },
    { class: "rework", from: "p11", to: "failed-p11" },
    { class: "rework", from: "p12", to: "failed-p12" },
    { class: "advance", from: "failed-p01", to: "p01" },
    { class: "advance", from: "failed-p02", to: "p02" },
    { class: "advance", from: "failed-p03", to: "p03" },
    { class: "advance", from: "failed-p04", to: "p04" },
    { class: "advance", from: "failed-p05", to: "p05" },
    { class: "advance", from: "failed-p06", to: "p06" },
    { class: "advance", from: "failed-p07", to: "p07" },
    { class: "advance", from: "failed-p08", to: "p08" },
    { class: "advance", from: "failed-p09", to: "p09" },
    { class: "advance", from: "failed-p10", to: "p10" },
    { class: "advance", from: "failed-p11", to: "p11" },
    { class: "advance", from: "failed-p12", to: "p12" },
  ],
} as const);

export default delamain;
